import Head from 'next/head';
import CoursePage from '../../components/Pages/CoursePage/CoursePage';

export default function Course() {
    return (
        <div>
            <Head>
                <title>Course | Udemy</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <CoursePage />
        </div>
    );
}