import { Flex, Text, Box, Container } from "@chakra-ui/react";
import Head from 'next/head';
import LoginPage from "../components/Pages/Login/Login";

export default function Login() {
    return (
        <div>
            <Head>
                <title>Login | Udemy</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <LoginPage />
        </div>
    );
}