import Head from 'next/head';
import CoursesDashboard from '../../components/Pages/CoursesDashboard/CoursesDashboard';

export default function Courses() {
    return (
        <div>
            <Head>
                <title>Courses | Udemy</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <CoursesDashboard />
        </div>
    );
}